version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_VERSION=1.26
    image: my-go-app:latest
    container_name: go-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Основные переменные окружения
      - SERVER_PORT=8080
      
      # База данных (пример)
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Us3r1pa55w0rd
      - DB_NAME=ef_mob
      
    volumes:
      # Монтирование конфигурационных файлов
      - ./configs:/app/configs:ro
      # Для логов (опционально)
      - ./logs:/app/logs
      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge